let currentUser,classes=[],topics=[],latestCredentials=[];
const pageMessage=document.getElementById("page-message");
const typeNames={timed_question:"Timed Question",progress_check:"Progress Check",prelim:"Prelim",homework:"Homework",assignment:"Assignment",general:"General Feedback"};

document.querySelectorAll(".sidebar button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".sidebar button,.panel").forEach(x=>x.classList.remove("active"));button.classList.add("active");document.getElementById(button.dataset.panel).classList.add("active");}));
function options(items,labelFn=x=>x.class_name){return `<option value="">-- Select --</option>`+items.map(x=>`<option value="${x.id}">${escapeHtml(labelFn(x))}</option>`).join("");}
function fillClassSelects(){for(const id of["pupil-class","roster-class","task-class","feedback-class"]){const el=document.getElementById(id);const old=el.value;el.innerHTML=options(classes);if(classes.some(x=>x.id===old))el.value=old;}document.getElementById("task-topic").innerHTML=options(topics,x=>x.topic_name);}

async function loadClasses(){const{data,error}=await db.from("classes").select("*, academic_years(label)").order("class_name");if(error)throw error;classes=data||[];document.getElementById("classes-body").innerHTML=classes.map(c=>`<tr><td>${escapeHtml(c.class_name)}</td><td>${escapeHtml(c.join_code)}</td><td>${escapeHtml(c.academic_years?.label)}</td><td>${c.active?"Active":"Archived"}</td><td><button class="secondary" onclick="editClass('${c.id}')">Edit</button> <button class="danger" onclick="archiveClass('${c.id}')">Archive</button></td></tr>`).join("")||"<tr><td colspan='5'>No classes yet.</td></tr>";fillClassSelects();}
async function editClass(id){const item=classes.find(c=>c.id===id);const className=prompt("Class name",item.class_name);if(className===null)return;const joinCode=prompt("Join code",item.join_code);if(joinCode===null)return;const{error}=await db.from("classes").update({class_name:className.trim(),join_code:joinCode.trim().toUpperCase()}).eq("id",id);if(error)return showMessage(pageMessage,error.message);await loadClasses();}
async function archiveClass(id){if(!confirm("Archive this class? Its existing feedback will be retained."))return;const{error}=await db.from("classes").update({active:false}).eq("id",id);if(error)return showMessage(pageMessage,error.message);await loadClasses();}
async function ensureDefaults(){let{data:topicData}=await db.from("topics").select("*").order("topic_name");if(!topicData?.length){const names=["Computer Systems","DDD","SDD"];await db.from("topics").insert(names.map(topic_name=>({teacher_id:currentUser.id,topic_name})));({data:topicData}=await db.from("topics").select("*").order("topic_name"));}topics=topicData||[];fillClassSelects();}
document.getElementById("class-form").addEventListener("submit",async e=>{e.preventDefault();try{const label=document.getElementById("academic-year").value.trim();let{data:year}=await db.from("academic_years").select("id").eq("label",label).maybeSingle();if(!year){const result=await db.from("academic_years").insert({label,created_by:currentUser.id}).select("id").single();if(result.error)throw result.error;year=result.data;}const{error}=await db.from("classes").insert({teacher_id:currentUser.id,academic_year_id:year.id,class_name:document.getElementById("class-name").value.trim(),join_code:document.getElementById("join-code").value.trim().toUpperCase()});if(error)throw error;e.target.reset();document.getElementById("academic-year").value="2026-27";showMessage(pageMessage,"Class added.","success");await loadClasses();}catch(error){showMessage(pageMessage,error.message);}});

document.getElementById("add-pupils").addEventListener("click",async()=>{const message=document.getElementById("pupil-message");try{const classId=document.getElementById("pupil-class").value;const rows=document.getElementById("pupil-data").value.split(/\r?\n/).filter(Boolean).map(line=>{const[name,code,band]=line.split(",").map(x=>x.trim());return{name,code,targetBand:Number(band)};});if(!classId||!rows.length)throw new Error("Select a class and enter pupil details.");const{data,error}=await db.functions.invoke("create-pupils",{body:{classId,pupils:rows}});if(error)throw error;if(data?.error)throw new Error(data.error);latestCredentials=data.credentials;document.getElementById("credentials-body").innerHTML=latestCredentials.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.code)}</td><td>${escapeHtml(x.temporaryPassword)}</td></tr>`).join("");document.getElementById("credentials").classList.remove("hidden");document.getElementById("pupil-data").value="";showMessage(message,`${latestCredentials.length} pupil accounts created.`,"success");await loadRoster();}catch(error){showMessage(message,error.message);}});
document.getElementById("download-credentials").addEventListener("click",()=>{const csv=["Name,Pupil Code,Temporary Password",...latestCredentials.map(x=>[x.name,x.code,x.temporaryPassword].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="temporary-pupil-logins.csv";a.click();URL.revokeObjectURL(a.href);});
async function loadRoster(){const classId=document.getElementById("roster-class").value||document.getElementById("pupil-class").value;if(!classId){document.getElementById("roster-body").innerHTML="<tr><td colspan='5'>Select a class.</td></tr>";return;}const{data}=await db.from("pupils").select("*").eq("class_id",classId).order("pupil_name");document.getElementById("roster-body").innerHTML=(data||[]).map(p=>`<tr><td>${escapeHtml(p.pupil_name)}</td><td>${escapeHtml(p.pupil_code)}</td><td>${p.target_band}</td><td>${p.active?"Active":"Archived"}</td><td><button class="secondary" onclick='editPupil(${JSON.stringify(JSON.stringify(p))})'>Edit</button> <button class="secondary" onclick="resetPupilPassword('${p.id}')">Reset password</button> <button class="danger" onclick="archivePupil('${p.id}')">Archive</button></td></tr>`).join("")||"<tr><td colspan='5'>No pupils.</td></tr>";}
async function managePupil(body){const{data,error}=await db.functions.invoke("manage-pupil",{body});if(error)throw error;if(data?.error)throw new Error(data.error);}
async function editPupil(serialised){const p=JSON.parse(serialised),name=prompt("Pupil name",p.pupil_name);if(name===null)return;const code=prompt("Pupil code",p.pupil_code);if(code===null)return;const targetBand=prompt("Target band (1-9)",p.target_band);if(targetBand===null)return;try{await managePupil({action:"update",pupilId:p.id,name,code,targetBand:Number(targetBand)});await loadRoster();}catch(error){showMessage(pageMessage,error.message);}}
async function resetPupilPassword(pupilId){const temporaryPassword=prompt("Enter a new temporary password (at least 8 characters)");if(temporaryPassword===null)return;try{await managePupil({action:"reset_password",pupilId,temporaryPassword});alert("Temporary password set. The pupil must replace it at next login.");}catch(error){showMessage(pageMessage,error.message);}}
async function archivePupil(pupilId){if(!confirm("Archive this pupil? Their feedback will be retained."))return;try{await managePupil({action:"archive",pupilId});await loadRoster();}catch(error){showMessage(pageMessage,error.message);}}
document.getElementById("roster-class").addEventListener("change",loadRoster);
document.getElementById("is-scored").addEventListener("change",e=>{document.getElementById("total-marks").disabled=!e.target.checked;if(!e.target.checked)document.getElementById("total-marks").value="";});
document.getElementById("task-form").addEventListener("submit",async e=>{e.preventDefault();try{const scored=document.getElementById("is-scored").checked;const{error}=await db.from("assessments").insert({class_id:document.getElementById("task-class").value,topic_id:document.getElementById("task-topic").value,assessment_type:document.getElementById("task-type").value,title:document.getElementById("task-title").value.trim(),is_scored:scored,total_marks:scored?Number(document.getElementById("total-marks").value):null,due_date:document.getElementById("task-date").value||null});if(error)throw error;e.target.reset();document.getElementById("is-scored").checked=true;showMessage(pageMessage,"Task created.","success");await loadTasks();}catch(error){showMessage(pageMessage,error.message);}});
async function loadTasks(){const{data}=await db.from("assessments").select("*,classes(class_name),topics(topic_name)").order("created_at",{ascending:false});document.getElementById("tasks-body").innerHTML=(data||[]).map(a=>`<tr><td>${escapeHtml(a.classes?.class_name)}</td><td>${escapeHtml(a.title)}</td><td>${escapeHtml(a.topics?.topic_name)}</td><td>${typeNames[a.assessment_type]}</td><td>${a.is_scored?a.total_marks:"Not scored"}</td><td>${a.active?`<button class="danger" onclick="archiveTask('${a.id}')">Archive</button>`:"Archived"}</td></tr>`).join("")||"<tr><td colspan='6'>No tasks.</td></tr>";}
async function archiveTask(id){if(!confirm("Archive this task? Existing submissions will remain visible."))return;const{error}=await db.from("assessments").update({active:false}).eq("id",id);if(error)return showMessage(pageMessage,error.message);await loadTasks();}
async function loadFeedback(){const classId=document.getElementById("feedback-class").value;if(!classId){document.getElementById("feedback-body").innerHTML="<tr><td colspan='8'>Select a class.</td></tr>";return;}const{data}=await db.from("feedback").select("*,pupils!inner(pupil_name,class_id),assessments!inner(title,class_id,topics(topic_name))").eq("pupils.class_id",classId).eq("assessments.class_id",classId).order("submitted_at",{ascending:false});document.getElementById("feedback-body").innerHTML=(data||[]).map(f=>`<tr><td>${escapeHtml(f.pupils?.pupil_name)}</td><td>${escapeHtml(f.assessments?.title)}</td><td>${escapeHtml(f.assessments?.topics?.topic_name)}</td><td>${f.score??"–"}</td><td>${f.percentage==null?"–":`${f.percentage}%`}</td><td>${f.current_band??"–"}</td><td><span class="badge ${f.self_evaluation}">${f.self_evaluation}</span></td><td>${escapeHtml(f.revision_comment)}</td></tr>`).join("")||"<tr><td colspan='8'>No feedback yet.</td></tr>";}
document.getElementById("feedback-class").addEventListener("change",loadFeedback);

(async()=>{const{data:{user}}=await db.auth.getUser();if(!user)return window.location.replace("index.html");const{data:profile}=await db.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="teacher")return signOut();currentUser=user;try{await loadClasses();await ensureDefaults();await loadTasks();}catch(error){showMessage(pageMessage,error.message);}})();
