let currentUser,classes=[],topics=[],tasks=[],rosterPupils=[],latestCredentials=[],editingTaskId=null,originalTask=null;
const pageMessage=document.getElementById("page-message");
const typeNames={timed_question:"Timed Question",progress_check:"Progress Check",prelim:"Prelim",homework:"Homework",assignment:"Assignment",general:"General Feedback"};
async function functionError(error){try{const body=await error.context?.json();return body?.error||error.message;}catch{return error.message;}}

document.querySelectorAll(".sidebar button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".sidebar button,.panel").forEach(x=>x.classList.remove("active"));button.classList.add("active");document.getElementById(button.dataset.panel).classList.add("active");}));
function options(items,labelFn=x=>x.class_name){return `<option value="">-- Select --</option>`+items.map(x=>`<option value="${x.id}">${escapeHtml(labelFn(x))}</option>`).join("");}
function fillClassSelects(){for(const id of["pupil-class","roster-class","task-class","feedback-class","action-class","action-task-class"]){const el=document.getElementById(id);const old=el.value;const label=id==="pupil-class"?x=>`${x.class_name} — ${x.join_code}`:x=>x.class_name;el.innerHTML=options(classes.filter(x=>x.active),label);if(classes.some(x=>x.id===old&&x.active))el.value=old;}const taskFilter=document.getElementById("task-list-class"),oldFilter=taskFilter.value;taskFilter.innerHTML=`<option value="">All classes</option>`+classes.map(item=>`<option value="${item.id}">${escapeHtml(item.class_name)}</option>`).join("");if(classes.some(item=>item.id===oldFilter))taskFilter.value=oldFilter;document.getElementById("task-topic").innerHTML=options(topics,x=>x.topic_name);}

async function loadClasses(){const{data,error}=await db.from("classes").select("*, academic_years(label)").order("class_name");if(error)throw error;classes=data||[];document.getElementById("classes-body").innerHTML=classes.map(c=>`<tr><td>${escapeHtml(c.class_name)}</td><td>${escapeHtml(c.join_code)}</td><td>${escapeHtml(c.academic_years?.label)}</td><td>${c.active?"Active":"Archived"}</td><td>${c.active?`<button class="secondary" onclick="editClass('${c.id}')">Edit</button> <button class="secondary" onclick="archiveClass('${c.id}')">Archive</button>`:`<button class="danger" onclick="deleteClass('${c.id}')">Delete permanently</button>`}</td></tr>`).join("")||"<tr><td colspan='5'>No classes yet.</td></tr>";fillClassSelects();}
async function editClass(id){const item=classes.find(c=>c.id===id);const className=prompt("Class name",item.class_name);if(className===null)return;const joinCode=prompt("Join code",item.join_code);if(joinCode===null)return;const{error}=await db.from("classes").update({class_name:className.trim(),join_code:joinCode.trim().toUpperCase()}).eq("id",id);if(error)return showMessage(pageMessage,error.message);await loadClasses();}
async function archiveClass(id){if(!confirm("Archive this class? Its existing feedback will be retained."))return;const{error}=await db.from("classes").update({active:false}).eq("id",id);if(error)return showMessage(pageMessage,error.message);await loadClasses();}
async function deleteClass(id){const item=classes.find(c=>c.id===id);if(!item)return;const typed=prompt(`This permanently deletes ${item.class_name}, including its pupil accounts, tasks and feedback.\n\nType the class name exactly to confirm:`);if(typed===null)return;if(typed!==item.class_name)return showMessage(pageMessage,"Class name did not match. Nothing was deleted.");try{const{data,error}=await db.functions.invoke("manage-class",{body:{classId:id,action:"delete"}});if(error)throw error;if(data?.error)throw new Error(data.error);showMessage(pageMessage,`${item.class_name} was permanently deleted.`,"success");await loadClasses();await loadTasks();}catch(error){showMessage(pageMessage,await functionError(error));}}
function isFixedActionTopic(topic){return ["computer systems","computer system","csystem","ddd","sdd"].includes(topic.topic_name.trim().toLowerCase());}
function actionTopicLabel(topic){return ["computer system","csystem"].includes(topic.topic_name.trim().toLowerCase())?"Computer Systems":topic.topic_name;}
function renderTopics(){const taskTopic=document.getElementById("task-topic"),oldTask=taskTopic.value;taskTopic.innerHTML=options(topics,x=>x.topic_name);if(topics.some(topic=>topic.id===oldTask))taskTopic.value=oldTask;const actionTopic=document.getElementById("action-task-topic"),oldAction=actionTopic.value,fixedTopics=topics.filter(isFixedActionTopic);actionTopic.innerHTML=options(fixedTopics,actionTopicLabel);if(fixedTopics.some(topic=>topic.id===oldAction))actionTopic.value=oldAction;}
async function ensureDefaults(){let{data:topicData}=await db.from("topics").select("*").order("topic_name");if(!topicData?.length){const names=["Computer Systems","DDD","SDD"];await db.from("topics").insert(names.map(topic_name=>({teacher_id:currentUser.id,topic_name})));({data:topicData}=await db.from("topics").select("*").order("topic_name"));}topics=topicData||[];fillClassSelects();renderTopics();}
document.getElementById("add-topic").addEventListener("click",async()=>{const input=document.getElementById("new-topic"),topicName=input.value.trim();if(!topicName)return showMessage(pageMessage,"Enter a topic name.");const{error}=await db.from("topics").insert({teacher_id:currentUser.id,topic_name:topicName});if(error)return showMessage(pageMessage,error.message);input.value="";showMessage(pageMessage,"Topic added.","success");await ensureDefaults();});
document.getElementById("class-form").addEventListener("submit",async e=>{e.preventDefault();try{const label=document.getElementById("academic-year").value.trim();let{data:year}=await db.from("academic_years").select("id").eq("label",label).maybeSingle();if(!year){const result=await db.from("academic_years").insert({label,created_by:currentUser.id}).select("id").single();if(result.error)throw result.error;year=result.data;}const{error}=await db.from("classes").insert({teacher_id:currentUser.id,academic_year_id:year.id,class_name:document.getElementById("class-name").value.trim(),join_code:document.getElementById("join-code").value.trim().toUpperCase()});if(error)throw error;e.target.reset();document.getElementById("academic-year").value="2026-27";showMessage(pageMessage,"Class added.","success");await loadClasses();}catch(error){showMessage(pageMessage,error.message);}});

document.getElementById("add-pupils").addEventListener("click",async()=>{
 const message=document.getElementById("pupil-message");
 try{
  const classId=document.getElementById("pupil-class").value;
  const names=document.getElementById("pupil-name").value.trim().split(/\r?\n/).map(value=>value.trim());
  const codes=document.getElementById("pupil-code").value.trim().split(/\r?\n/).map(value=>value.trim().toUpperCase());
  const targetBand=Number(document.getElementById("pupil-band").value);
  if(!classId)throw new Error("Select one class / join code for these pupils.");
  if(!names.length||!codes.length)throw new Error("Enter the pupil names and matching login codes, one per line.");
  if(names.length!==codes.length)throw new Error(`There are ${names.length} pupil names but ${codes.length} login codes. Each pupil needs one matching login code.`);
  if(names.some((name,index)=>!name||!codes[index]))throw new Error("Remove any blank lines. Each pupil name must line up with one login code.");
  if(names.length>30)throw new Error("You can create a maximum of 30 pupils at a time.");
  const pupils=names.map((name,index)=>({name,code:codes[index],targetBand}));
  const{data,error}=await db.functions.invoke("create-pupils",{body:{classId,pupils}});
  if(error)throw error;if(data?.error)throw new Error(data.error);
  latestCredentials=data.credentials;
  document.getElementById("credentials-body").innerHTML=latestCredentials.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.code)}</td><td>${escapeHtml(x.temporaryPassword)}</td></tr>`).join("");
  document.getElementById("credentials").classList.remove("hidden");
  document.getElementById("pupil-name").value="";document.getElementById("pupil-code").value="";document.getElementById("pupil-band").value="2";
  document.getElementById("roster-class").value=classId;
  showMessage(message,`${latestCredentials.length} pupil ${latestCredentials.length===1?"account":"accounts"} created.`,"success");
  await loadRoster();
 }catch(error){showMessage(message,await functionError(error));}
});
document.getElementById("download-credentials").addEventListener("click",()=>{const csv=["Name,Pupil Code,Temporary Password",...latestCredentials.map(x=>[x.name,x.code,x.temporaryPassword].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="temporary-pupil-logins.csv";a.click();URL.revokeObjectURL(a.href);});
function bandOptions(selected){return Array.from({length:9},(_,index)=>index+1).map(band=>`<option value="${band}"${band===Number(selected)?" selected":""}>Band ${band}</option>`).join("");}
async function loadRoster(){const classId=document.getElementById("roster-class").value||document.getElementById("pupil-class").value;if(!classId){rosterPupils=[];document.getElementById("roster-body").innerHTML="<tr><td colspan='5'>Select a class.</td></tr>";return;}const{data,error}=await db.from("pupils").select("*").eq("class_id",classId).order("pupil_code",{ascending:true});if(error)return showMessage(pageMessage,error.message);rosterPupils=data||[];document.getElementById("roster-body").innerHTML=rosterPupils.map(p=>`<tr><td>${escapeHtml(p.pupil_name)}</td><td>${escapeHtml(p.pupil_code)}</td><td><select class="roster-band" aria-label="Target band for ${escapeHtml(p.pupil_name)}" onchange="changeTargetBand('${p.id}',this)" ${p.active?"":"disabled"}>${bandOptions(p.target_band)}</select></td><td>${p.active?"Active":"Archived"}</td><td>${p.active?`<button class="secondary" onclick='editPupil(${JSON.stringify(JSON.stringify(p))})'>Edit</button> <button class="secondary" onclick="resetPupilPassword('${p.id}')">Reset password</button> <button class="secondary" onclick="archivePupil('${p.id}')">Archive</button>`:`<button class="danger" onclick="deletePupil('${p.id}')">Delete permanently</button>`}</td></tr>`).join("")||"<tr><td colspan='5'>No pupils.</td></tr>";}
async function managePupil(body){const{data,error}=await db.functions.invoke("manage-pupil",{body});if(error)throw error;if(data?.error)throw new Error(data.error);}
async function editPupil(serialised){const p=JSON.parse(serialised),name=prompt("Pupil name",p.pupil_name);if(name===null)return;const code=prompt("Pupil code",p.pupil_code);if(code===null)return;try{await managePupil({action:"update",pupilId:p.id,name,code,targetBand:Number(p.target_band)});await loadRoster();}catch(error){showMessage(pageMessage,error.message);}}
async function changeTargetBand(pupilId,select){const pupil=rosterPupils.find(item=>item.id===pupilId),previous=pupil?.target_band;select.disabled=true;try{if(!pupil)throw new Error("Pupil not found.");await managePupil({action:"update",pupilId,name:pupil.pupil_name,code:pupil.pupil_code,targetBand:Number(select.value)});pupil.target_band=Number(select.value);showMessage(pageMessage,"Target band updated.","success");}catch(error){if(previous)select.value=String(previous);showMessage(pageMessage,error.message);}finally{select.disabled=false;}}
async function resetPupilPassword(pupilId){const temporaryPassword=prompt("Enter a new temporary password (at least 8 characters)");if(temporaryPassword===null)return;try{await managePupil({action:"reset_password",pupilId,temporaryPassword});alert("Temporary password set. The pupil must replace it at next login.");}catch(error){showMessage(pageMessage,error.message);}}
async function archivePupil(pupilId){if(!confirm("Archive this pupil? Their feedback will be retained."))return;try{await managePupil({action:"archive",pupilId});await loadRoster();}catch(error){showMessage(pageMessage,error.message);}}
async function deletePupil(pupilId){const pupil=rosterPupils.find(item=>item.id===pupilId);if(!pupil||pupil.active)return;const typed=prompt(`This permanently deletes ${pupil.pupil_name}, including their login and feedback.\n\nType the pupil login code ${pupil.pupil_code} to confirm:`);if(typed===null)return;if(typed.trim().toUpperCase()!==pupil.pupil_code)return showMessage(pageMessage,"Login code did not match. Nothing was deleted.");try{await managePupil({action:"delete",pupilId});showMessage(pageMessage,`${pupil.pupil_name} was permanently deleted.`,"success");await loadRoster();}catch(error){showMessage(pageMessage,await functionError(error));}}
document.getElementById("roster-class").addEventListener("change",loadRoster);
document.getElementById("is-scored").addEventListener("change",e=>{document.getElementById("total-marks").disabled=!e.target.checked;if(!e.target.checked)document.getElementById("total-marks").value="";});
function resetTaskForm(){editingTaskId=null;originalTask=null;const form=document.getElementById("task-form");form.reset();document.getElementById("is-scored").checked=true;document.getElementById("total-marks").disabled=false;document.getElementById("task-submit").textContent="Create task";document.getElementById("cancel-task-edit").classList.add("hidden");}
document.getElementById("cancel-task-edit").addEventListener("click",resetTaskForm);
document.getElementById("task-form").addEventListener("submit",async e=>{e.preventDefault();try{const scored=document.getElementById("is-scored").checked;const taskData={class_id:document.getElementById("task-class").value,topic_id:document.getElementById("task-topic").value,assessment_type:document.getElementById("task-type").value,title:document.getElementById("task-title").value.trim(),is_scored:scored,total_marks:scored?Number(document.getElementById("total-marks").value):null,due_date:document.getElementById("task-date").value||null};if(editingTaskId){const{count,error:countError}=await db.from("feedback").select("id",{count:"exact",head:true}).eq("assessment_id",editingTaskId);if(countError)throw countError;if(count){const protectedChange=taskData.class_id!==originalTask.class_id||taskData.assessment_type!==originalTask.assessment_type||taskData.is_scored!==originalTask.is_scored||Number(taskData.total_marks)!==Number(originalTask.total_marks);if(protectedChange)throw new Error("Class, activity type, scored status and total marks cannot be changed after pupil feedback has been submitted.");}const{error}=await db.from("assessments").update(taskData).eq("id",editingTaskId);if(error)throw error;showMessage(pageMessage,"Task updated.","success");}else{const{error}=await db.from("assessments").insert(taskData);if(error)throw error;showMessage(pageMessage,"Task created.","success");}resetTaskForm();await loadTasks();}catch(error){showMessage(pageMessage,error.message);}});
function renderTasks(){const classId=document.getElementById("task-list-class").value,visibleTasks=tasks.filter(item=>!classId||item.class_id===classId);document.getElementById("tasks-body").innerHTML=visibleTasks.map(a=>`<tr><td>${escapeHtml(a.classes?.class_name)}</td><td>${escapeHtml(a.title)}</td><td>${escapeHtml(a.topics?.topic_name)}</td><td>${typeNames[a.assessment_type]}</td><td>${a.is_scored?a.total_marks:"Not scored"}</td><td>${a.active?`<button class="secondary" onclick="editTask('${a.id}')">Edit</button>`:"Archived"}</td></tr>`).join("")||"<tr><td colspan='6'>No tasks for this class.</td></tr>";}
async function loadTasks(){const{data,error}=await db.from("assessments").select("*,classes(class_name),topics(topic_name)").order("created_at",{ascending:false});if(error)return showMessage(pageMessage,error.message);tasks=data||[];renderTasks();}
document.getElementById("task-list-class").addEventListener("change",renderTasks);
function editTask(id){const task=tasks.find(item=>item.id===id);if(!task)return;editingTaskId=id;originalTask={...task};document.getElementById("task-class").value=task.class_id;document.getElementById("task-topic").value=task.topic_id;document.getElementById("task-type").value=task.assessment_type;document.getElementById("task-title").value=task.title;document.getElementById("task-date").value=task.due_date||"";document.getElementById("is-scored").checked=task.is_scored;document.getElementById("total-marks").value=task.total_marks??"";document.getElementById("total-marks").disabled=!task.is_scored;document.getElementById("task-submit").textContent="Save changes";document.getElementById("cancel-task-edit").classList.remove("hidden");document.getElementById("task-form").scrollIntoView({behavior:"smooth",block:"start"});}
let classFeedback=[],visibleFeedbackRows=[];
const feedbackPupil=document.getElementById("feedback-pupil");
const feedbackTopic=document.getElementById("feedback-topic");
const feedbackTask=document.getElementById("feedback-task");
const feedbackPriority=document.getElementById("feedback-priority");
function allOptions(items,labelFn){return `<option value="">All</option>`+items.map(item=>`<option value="${item.id}">${escapeHtml(labelFn(item))}</option>`).join("");}
function teacherBandColour(band,targetBand){if(band==null)return"";if(band<=targetBand)return"green";if(band>=7)return"red";if(band%2===0&&band-targetBand===1)return"amber";return"red";}
function feedbackRow(f){return `<tr><td>${escapeHtml(f.pupils?.pupil_name)}</td><td>${escapeHtml(f.assessments?.title)}</td><td>${escapeHtml(f.assessments?.topics?.topic_name)}</td><td>${f.score??"–"}</td><td>${f.percentage==null?"–":`${f.percentage}%`}</td><td>${f.current_band==null?"–":`<span class="badge ${teacherBandColour(Number(f.current_band),Number(f.pupils?.target_band))}">Band ${f.current_band}</span>`}</td><td><span class="badge ${f.self_evaluation}">${f.self_evaluation}</span></td><td>${escapeHtml(f.revision_comment)}</td></tr>`;}
function averagePercentage(rows){const scored=rows.filter(item=>item.percentage!=null);return scored.length?scored.reduce((sum,item)=>sum+Number(item.percentage),0)/scored.length:null;}
function sortedByScore(rows){return [...rows].sort((a,b)=>(a.percentage==null?Infinity:Number(a.percentage))-(b.percentage==null?Infinity:Number(b.percentage)));}
function renderFeedback(){
 const pupilId=feedbackPupil.value,topicId=feedbackTopic.value,taskId=feedbackTask.value;
 const rows=classFeedback.filter(item=>(!pupilId||item.pupil_id===pupilId)&&(!topicId||item.assessments?.topic_id===topicId)&&(!taskId||item.assessment_id===taskId));
 const mode=feedbackPriority.value;
 let html="";
 if(mode==="normal"){visibleFeedbackRows=rows;html=rows.map(feedbackRow).join("");}
 else if(pupilId){visibleFeedbackRows=sortedByScore(rows);html=visibleFeedbackRows.map(feedbackRow).join("");}
 else{
  const groupByTask=mode==="task_average",groups=new Map();
  for(const row of rows){const key=groupByTask?row.assessment_id:row.pupil_id;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}
  const ranked=[...groups.values()].map(groupRows=>({rows:groupRows,average:averagePercentage(groupRows)})).sort((a,b)=>(a.average??Infinity)-(b.average??Infinity));
  visibleFeedbackRows=ranked.flatMap(group=>sortedByScore(group.rows));
  html=ranked.map((group,index)=>{const first=group.rows[0],label=groupByTask?first.assessments?.title:first.pupils?.pupil_name,detail=group.average==null?"No scored feedback":`${group.average.toFixed(1)}% average`,count=groupByTask?`${new Set(group.rows.map(item=>item.pupil_id)).size} pupil${new Set(group.rows.map(item=>item.pupil_id)).size===1?"":"s"}`:`${group.rows.filter(item=>item.percentage!=null).length} scored task${group.rows.filter(item=>item.percentage!=null).length===1?"":"s"}`;return `<tr class="priority-group"><td colspan="8">Priority ${index+1}: ${escapeHtml(label)} — ${detail} (${count})</td></tr>`+sortedByScore(group.rows).map(feedbackRow).join("");}).join("");
 }
 document.getElementById("feedback-body").innerHTML=html||"<tr><td colspan='8'>No feedback matches these filters.</td></tr>";
 document.getElementById("download-feedback-log").disabled=!visibleFeedbackRows.length;
}
function fillFeedbackTasks(){
 const topicId=feedbackTopic.value,oldTask=feedbackTask.value;
 const available=tasks.filter(task=>task.class_id===document.getElementById("feedback-class").value&&(!topicId||task.topic_id===topicId));
 feedbackTask.innerHTML=allOptions(available,item=>item.title).replace(">All<",">All tasks<");
 if(available.some(item=>item.id===oldTask))feedbackTask.value=oldTask;
}
async function loadFeedback(){
 const classId=document.getElementById("feedback-class").value;
 feedbackPupil.innerHTML='<option value="">All pupils</option>';feedbackTopic.innerHTML='<option value="">All topics</option>';feedbackTask.innerHTML='<option value="">All tasks</option>';
 for(const element of[feedbackPupil,feedbackTopic,feedbackTask,feedbackPriority])element.disabled=!classId;
 if(!classId){classFeedback=[];visibleFeedbackRows=[];document.getElementById("download-feedback-log").disabled=true;document.getElementById("feedback-body").innerHTML="<tr><td colspan='8'>Select a class.</td></tr>";return;}
 const[{data:pupilData,error:pupilError},{data,error}]=await Promise.all([
  db.from("pupils").select("id,pupil_name").eq("class_id",classId).order("pupil_name"),
  db.from("feedback").select("*,pupils!inner(pupil_name,class_id,target_band),assessments!inner(id,title,class_id,topic_id,topics(id,topic_name))").eq("pupils.class_id",classId).eq("assessments.class_id",classId).order("submitted_at",{ascending:false})
 ]);
 if(pupilError||error){showMessage(pageMessage,(pupilError||error).message);return;}
 classFeedback=data||[];
 feedbackPupil.innerHTML=allOptions(pupilData||[],item=>item.pupil_name).replace(">All<",">All pupils<");
 const classTasks=tasks.filter(task=>task.class_id===classId);
 const topicIds=new Set(classTasks.map(task=>task.topic_id));
 feedbackTopic.innerHTML=allOptions(topics.filter(topic=>topicIds.has(topic.id)),item=>item.topic_name).replace(">All<",">All topics<");
 fillFeedbackTasks();renderFeedback();
}
document.getElementById("feedback-class").addEventListener("change",loadFeedback);
feedbackPupil.addEventListener("change",renderFeedback);
feedbackTopic.addEventListener("change",()=>{fillFeedbackTasks();renderFeedback();});
feedbackTask.addEventListener("change",renderFeedback);
feedbackPriority.addEventListener("change",renderFeedback);
document.getElementById("download-feedback-log").addEventListener("click",()=>{if(!visibleFeedbackRows.length)return;const{jsPDF}=window.jspdf||{};if(!jsPDF)return alert("The PDF tool did not load. Refresh the page and try again.");const doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const classLabel=document.getElementById("feedback-class").selectedOptions[0]?.text||"";doc.setFontSize(18);doc.setTextColor(15,23,42);doc.text("Teacher Feedback Log",14,16);doc.setFontSize(10);doc.text(`Class: ${classLabel}`,14,23);doc.text(`Pupil: ${feedbackPupil.selectedOptions[0]?.text||"All pupils"}`,14,29);doc.text(`Topic: ${feedbackTopic.selectedOptions[0]?.text||"All topics"}`,90,23);doc.text(`Task: ${feedbackTask.selectedOptions[0]?.text||"All tasks"}`,90,29);doc.text(`Order: ${feedbackPriority.selectedOptions[0]?.text||""}`,190,23);const rows=visibleFeedbackRows.map(item=>[item.pupils?.pupil_name||"",item.assessments?.title||"",item.assessments?.topics?.topic_name||"",item.score==null?"-":String(item.score),item.percentage==null?"-":`${item.percentage}%`,item.current_band==null?"-":`Band ${item.current_band}`,item.self_evaluation||"",item.revision_comment||""]);doc.autoTable({startY:36,head:[["Pupil","Task","Topic","Score","%","Band","Evaluation","Comment"]],body:rows,theme:"grid",styles:{fontSize:8,cellPadding:2,overflow:"linebreak",valign:"top"},headStyles:{fillColor:[15,23,42],textColor:255},columnStyles:{0:{cellWidth:27},1:{cellWidth:42},2:{cellWidth:34},3:{cellWidth:16},4:{cellWidth:16},5:{cellWidth:19},6:{cellWidth:23},7:{cellWidth:"auto"}},margin:{left:10,right:10}});doc.save(`${classLabel.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"class"}-feedback.pdf`);});

let actionPointTasks=[],editingActionTaskId=null,teacherActionPoints=[],visibleTeacherActionPoints=[];
const actionClass=document.getElementById("action-class"),actionPupil=document.getElementById("action-pupil"),actionType=document.getElementById("action-type"),actionStatus=document.getElementById("action-status"),actionTopic=document.getElementById("action-topic"),actionTask=document.getElementById("action-task");
const actionTypeNames={general_feedback:"Homework",class_note:"Class note",revision_tip:"Revision tip",assignment_feedback:"Assignment"};
async function loadActionPointTasks(){const{data,error}=await db.from("action_point_tasks").select("*,classes(class_name),topics(topic_name)").order("created_at",{ascending:false});if(error)return showMessage(pageMessage,error.message);actionPointTasks=data||[];document.getElementById("action-tasks-body").innerHTML=actionPointTasks.map(item=>`<tr><td>${escapeHtml(item.classes?.class_name)}</td><td>${escapeHtml(item.topics?.topic_name)}</td><td>${escapeHtml(item.title)}</td><td><button class="secondary" type="button" onclick="editActionPointTask('${item.id}')">Edit</button></td></tr>`).join("")||"<tr><td colspan='4'>No action-point tasks yet.</td></tr>";fillActionTasks();}
function resetActionTaskForm(){editingActionTaskId=null;document.getElementById("action-task-form").reset();document.getElementById("action-task-submit").textContent="Add action-point task";document.getElementById("cancel-action-task-edit").classList.add("hidden");}
document.getElementById("cancel-action-task-edit").addEventListener("click",resetActionTaskForm);
document.getElementById("action-task-form").addEventListener("submit",async event=>{event.preventDefault();const row={class_id:document.getElementById("action-task-class").value,topic_id:document.getElementById("action-task-topic").value,title:document.getElementById("action-task-title").value.trim()};if(!row.class_id||!row.topic_id||!row.title)return showMessage(pageMessage,"Select a class and topic, then enter an action-point task.");const wasEditing=Boolean(editingActionTaskId),result=wasEditing?await db.from("action_point_tasks").update(row).eq("id",editingActionTaskId):await db.from("action_point_tasks").insert(row);if(result.error)return showMessage(pageMessage,result.error.message);showMessage(pageMessage,wasEditing?"Action-point task updated.":"Action-point task added.","success");resetActionTaskForm();await loadActionPointTasks();});
function editActionPointTask(id){const item=actionPointTasks.find(task=>task.id===id);if(!item)return;editingActionTaskId=id;document.getElementById("action-task-class").value=item.class_id;document.getElementById("action-task-topic").value=item.topic_id;document.getElementById("action-task-title").value=item.title;document.getElementById("action-task-submit").textContent="Save changes";document.getElementById("cancel-action-task-edit").classList.remove("hidden");document.getElementById("action-task-form").scrollIntoView({behavior:"smooth",block:"start"});}
function fillActionTasks(){const topicId=actionTopic.value,old=actionTask.value,available=actionPointTasks.filter(item=>item.class_id===actionClass.value&&(!topicId||item.topic_id===topicId));actionTask.innerHTML=allOptions(available,item=>item.title).replace(">All<",">All tasks<");if(available.some(item=>item.id===old))actionTask.value=old;}
function renderTeacherActionPoints(){const pupilId=actionPupil.value,type=actionType.value,status=actionStatus.value,topicId=actionTopic.value,taskId=actionTask.value;visibleTeacherActionPoints=teacherActionPoints.filter(item=>(!pupilId||item.pupil_id===pupilId)&&(!type||item.note_type===type)&&(!status||(status==="actioned"?item.actioned:!item.actioned))&&(!topicId||item.topic_id===topicId)&&(!taskId||item.action_task_id===taskId));const openCount=visibleTeacherActionPoints.filter(item=>!item.actioned).length,count=document.getElementById("teacher-action-count");count.textContent=`${openCount} to action`;count.className=`badge ${openCount?"amber":"green"}`;document.getElementById("teacher-actions-body").innerHTML=visibleTeacherActionPoints.map(item=>`<tr class="${item.actioned?"actioned-row":""}"><td>${escapeHtml(item.pupils?.pupil_name)}</td><td>${escapeHtml(actionTypeNames[item.note_type])}</td><td>${escapeHtml(item.action_point_tasks?.title||"–")}</td><td>${escapeHtml(item.topics?.topic_name||"–")}</td><td class="note-comment">${escapeHtml(item.revision_comment)}</td><td><span class="badge ${item.actioned?"green":"amber"}">${item.actioned?"Actioned":"To action"}</span></td><td>${new Date(item.created_at).toLocaleDateString("en-GB")}</td></tr>`).join("")||"<tr><td colspan='7'>No action points match these filters.</td></tr>";}
async function loadTeacherActionPoints(){const classId=actionClass.value;for(const element of[actionPupil,actionType,actionStatus,actionTopic,actionTask])element.disabled=!classId;if(!classId){teacherActionPoints=[];visibleTeacherActionPoints=[];document.getElementById("teacher-actions-body").innerHTML="<tr><td colspan='7'>Select a class.</td></tr>";return;}const[{data:pupilData,error:pupilError},{data,error}]=await Promise.all([db.from("pupils").select("id,pupil_name").eq("class_id",classId).order("pupil_name"),db.from("pupil_action_points").select("*,pupils!inner(pupil_name,class_id),action_point_tasks(title,topic_id),topics(topic_name)").eq("pupils.class_id",classId).order("created_at",{ascending:false})]);if(pupilError||error)return showMessage(pageMessage,(pupilError||error).message);teacherActionPoints=data||[];actionPupil.innerHTML=allOptions(pupilData||[],item=>item.pupil_name).replace(">All<",">All pupils<");const classActionTasks=actionPointTasks.filter(item=>item.class_id===classId),topicIds=new Set(classActionTasks.map(item=>item.topic_id));actionTopic.innerHTML=allOptions(topics.filter(item=>topicIds.has(item.id)&&isFixedActionTopic(item)),actionTopicLabel).replace(">All<",">All topics<");fillActionTasks();renderTeacherActionPoints();}
actionClass.addEventListener("change",loadTeacherActionPoints);
actionPupil.addEventListener("change",renderTeacherActionPoints);
actionType.addEventListener("change",renderTeacherActionPoints);
actionStatus.addEventListener("change",renderTeacherActionPoints);
actionTopic.addEventListener("change",()=>{fillActionTasks();renderTeacherActionPoints();});
actionTask.addEventListener("change",renderTeacherActionPoints);

(async()=>{const{data:{user}}=await db.auth.getUser();if(!user)return window.location.replace("index.html");const{data:profile}=await db.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="teacher")return signOut();currentUser=user;try{await loadClasses();await ensureDefaults();await loadTasks();await loadActionPointTasks();}catch(error){showMessage(pageMessage,error.message);}})();
