let user,pupil,assessments=[],history=[],charts={},targetPercentage=null;
const typeNames={timed_question:"Timed Question",progress_check:"Progress Check",prelim:"Prelim",homework:"Homework",assignment:"Assignment",general:"General Feedback"};
const centreTextPlugin={id:"centreText",afterDraw(chart,args,options){if(!options?.text)return;const{x,y}=chart.getDatasetMeta(0).data[0]||{x:chart.width/2,y:chart.height/2};const context=chart.ctx;context.save();context.textAlign="center";context.textBaseline="middle";context.fillStyle="#0f172a";context.font="700 28px Arial";context.fillText(options.text,x,y+20);context.restore();}};
const targetLinePlugin={id:"targetLine",afterDraw(chart,args,options){if(options?.value==null||!chart.chartArea)return;const{ctx,chartArea:{left,right},scales:{y}}=chart;const lineY=y.getPixelForValue(options.value);ctx.save();ctx.beginPath();ctx.setLineDash([7,5]);ctx.lineWidth=2;ctx.strokeStyle="#dc2626";ctx.moveTo(left,lineY);ctx.lineTo(right,lineY);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#b91c1c";ctx.font="700 11px Arial";ctx.textAlign="right";ctx.fillText(options.label,right-4,lineY-6);ctx.restore();}};

async function loadPupil(){const{data,error}=await db.from("pupils").select("*,classes(class_name)").eq("id",user.id).single();if(error)throw error;pupil=data;const{data:boundary}=await db.from("grade_boundaries").select("minimum_percentage").eq("band",pupil.target_band).single();targetPercentage=boundary?Number(boundary.minimum_percentage):null;document.getElementById("pupil-heading").textContent=`${pupil.pupil_name}'s feedback`;document.getElementById("class-name").textContent=pupil.classes.class_name;document.getElementById("target-band").textContent=`Band ${pupil.target_band}`;}
async function loadAssessments(){const{data,error}=await db.from("assessments").select("*,topics(topic_name)").eq("class_id",pupil.class_id).eq("active",true).order("created_at",{ascending:false});if(error)throw error;assessments=data||[];document.getElementById("assessment").innerHTML=`<option value="">-- Choose task --</option>`+assessments.map(a=>`<option value="${a.id}">${escapeHtml(a.title)} (${escapeHtml(a.topics?.topic_name)})</option>`).join("");updateScoreInput();}
function updateScoreInput(){const task=assessments.find(a=>a.id===document.getElementById("assessment").value);const group=document.getElementById("score-group"),score=document.getElementById("score");group.classList.toggle("hidden",!task?.is_scored);score.required=Boolean(task?.is_scored);score.max=task?.total_marks||"";group.querySelector("label").textContent=task?.is_scored?`Score (out of ${task.total_marks})`:"Score";}
document.getElementById("assessment").addEventListener("change",updateScoreInput);
document.getElementById("feedback-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.getElementById("feedback-message");try{const task=assessments.find(a=>a.id===document.getElementById("assessment").value);if(!task)throw new Error("Choose a task.");const row={assessment_id:task.id,pupil_id:user.id,score:task.is_scored?Number(document.getElementById("score").value):null,self_evaluation:new FormData(e.target).get("evaluation"),revision_comment:document.getElementById("comment").value.trim()||null};const{error}=await db.from("feedback").upsert(row,{onConflict:"assessment_id,pupil_id"});if(error)throw error;e.target.reset();updateScoreInput();showMessage(message,"Feedback saved.","success");await loadHistory();}catch(error){showMessage(message,error.message);}});
async function loadHistory(){const{data,error}=await db.from("feedback").select("*,assessments(title,assessment_type,total_marks,topics(topic_name))").eq("pupil_id",user.id).order("submitted_at");if(error)throw error;history=data||[];const latest=[...history].reverse().find(x=>x.current_band);document.getElementById("latest-band").textContent=latest?`Band ${latest.current_band}`:"No scored result yet";document.getElementById("history-body").innerHTML=[...history].reverse().map(f=>`<tr><td>${escapeHtml(f.assessments?.title)}</td><td>${escapeHtml(f.assessments?.topics?.topic_name)}</td><td>${typeNames[f.assessments?.assessment_type]}</td><td>${f.score==null?"–":`${f.score}/${f.assessments.total_marks}`}</td><td>${f.percentage==null?"–":`${f.percentage}%`}</td><td>${f.current_band??"–"}</td><td><span class="badge ${f.self_evaluation}">${f.self_evaluation}</span></td><td>${escapeHtml(f.revision_comment)}</td></tr>`).join("")||"<tr><td colspan='8'>No feedback submitted yet.</td></tr>";renderCharts();}
function renderCharts(){Object.values(charts).forEach(chart=>chart?.destroy());charts={};const scored=history.filter(item=>item.percentage!=null);const average=scored.length?Math.round(scored.reduce((sum,item)=>sum+Number(item.percentage),0)/scored.length*10)/10:0;const gaugeColour=average>=70?"#2faa4f":average>=55?"#ffbd17":"#f04438";charts.gauge=new Chart(document.getElementById("score-gauge"),{type:"doughnut",plugins:[centreTextPlugin],data:{datasets:[{data:[average,100-average],backgroundColor:[gaugeColour,"#e5e7eb"],borderWidth:0,circumference:180,rotation:270}]},options:{responsive:true,maintainAspectRatio:false,cutout:"72%",plugins:{legend:{display:false},tooltip:{enabled:false},centreText:{text:`${average}%`}}}});document.getElementById("gauge-note").textContent=scored.length?`Average from ${scored.length} scored ${scored.length===1?"assessment":"assessments"}`:"No scored results yet";
const evaluationCounts=["green","amber","red"].map(colour=>history.filter(item=>item.self_evaluation===colour).length);const hasEvaluations=evaluationCounts.some(Boolean);charts.evaluation=new Chart(document.getElementById("evaluation-chart"),{type:"doughnut",data:{labels:hasEvaluations?["Green","Amber","Red"]:["No feedback"],datasets:[{data:hasEvaluations?evaluationCounts:[1],backgroundColor:hasEvaluations?["#2faa4f","#ffbd17","#f04438"]:["#e5e7eb"],borderWidth:2,borderColor:"#fff"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"},tooltip:{enabled:hasEvaluations}}}});
const progressTypes=new Set(["timed_question","progress_check","prelim"]);const progressRows=scored.filter(item=>progressTypes.has(item.assessments?.assessment_type));const shortType={timed_question:"TQ",progress_check:"PC",prelim:"Prelim"};const datasets=[{label:"Score",data:progressRows.map(item=>Number(item.percentage)),borderColor:"#654bb3",backgroundColor:"#654bb3",pointRadius:4,tension:.2}];charts.progress=new Chart(document.getElementById("progress-chart"),{type:"line",plugins:[targetLinePlugin],data:{labels:progressRows.map(item=>`${item.assessments.title} (${shortType[item.assessments.assessment_type]})`),datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"bottom"},targetLine:{value:targetPercentage,label:targetPercentage==null?"":`Band ${pupil.target_band}: ${targetPercentage}%`},tooltip:{callbacks:{afterLabel:context=>progressRows[context.dataIndex].assessments.topics?.topic_name||""}}},scales:{y:{min:0,max:100,ticks:{callback:value=>`${value}%`},title:{display:true,text:"Percentage"}},x:{ticks:{maxRotation:35,minRotation:0}}}}});document.getElementById("target-note").textContent=targetPercentage==null?"Target percentage unavailable.":`Dashed line: Band ${pupil.target_band} target (${targetPercentage}% and above).`;}
document.getElementById("password-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.getElementById("password-message"),password=document.getElementById("new-password").value;if(password!==document.getElementById("confirm-password").value)return showMessage(message,"The passwords do not match.");const{error}=await db.auth.updateUser({password});if(error)return showMessage(message,error.message);const update=await db.rpc("complete_password_change");if(update.error)return showMessage(message,update.error.message);document.getElementById("password-card").classList.add("hidden");document.getElementById("portal").classList.remove("hidden");await initialisePortal();});
async function initialisePortal(){await loadPupil();await loadAssessments();await loadHistory();}
(async()=>{const result=await db.auth.getUser();user=result.data.user;if(!user)return window.location.replace("index.html");const{data:profile}=await db.from("profiles").select("role,must_change_password").eq("id",user.id).single();if(profile?.role!=="pupil")return signOut();if(profile.must_change_password)document.getElementById("password-card").classList.remove("hidden");else{document.getElementById("portal").classList.remove("hidden");await initialisePortal();}})();
