let user,pupil,assessments=[],history=[],charts={};
const typeNames={timed_question:"Timed Question",progress_check:"Progress Check",prelim:"Prelim",homework:"Homework",assignment:"Assignment",general:"General Feedback"};

async function loadPupil(){const{data,error}=await db.from("pupils").select("*,classes(class_name)").eq("id",user.id).single();if(error)throw error;pupil=data;document.getElementById("pupil-heading").textContent=`${pupil.pupil_name}'s feedback`;document.getElementById("class-name").textContent=pupil.classes.class_name;document.getElementById("target-band").textContent=`Band ${pupil.target_band}`;}
async function loadAssessments(){const{data,error}=await db.from("assessments").select("*,topics(topic_name)").eq("class_id",pupil.class_id).eq("active",true).order("created_at",{ascending:false});if(error)throw error;assessments=data||[];document.getElementById("assessment").innerHTML=`<option value="">-- Choose task --</option>`+assessments.map(a=>`<option value="${a.id}">${escapeHtml(a.title)} (${escapeHtml(a.topics?.topic_name)})</option>`).join("");updateScoreInput();}
function updateScoreInput(){const task=assessments.find(a=>a.id===document.getElementById("assessment").value);const group=document.getElementById("score-group"),score=document.getElementById("score");group.classList.toggle("hidden",!task?.is_scored);score.required=Boolean(task?.is_scored);score.max=task?.total_marks||"";group.querySelector("label").textContent=task?.is_scored?`Score (out of ${task.total_marks})`:"Score";}
document.getElementById("assessment").addEventListener("change",updateScoreInput);
document.getElementById("feedback-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.getElementById("feedback-message");try{const task=assessments.find(a=>a.id===document.getElementById("assessment").value);if(!task)throw new Error("Choose a task.");const row={assessment_id:task.id,pupil_id:user.id,score:task.is_scored?Number(document.getElementById("score").value):null,self_evaluation:new FormData(e.target).get("evaluation"),revision_comment:document.getElementById("comment").value.trim()||null};const{error}=await db.from("feedback").upsert(row,{onConflict:"assessment_id,pupil_id"});if(error)throw error;e.target.reset();updateScoreInput();showMessage(message,"Feedback saved.","success");await loadHistory();}catch(error){showMessage(message,error.message);}});
async function loadHistory(){const{data,error}=await db.from("feedback").select("*,assessments(title,assessment_type,total_marks,topics(topic_name))").eq("pupil_id",user.id).order("submitted_at");if(error)throw error;history=data||[];const latest=[...history].reverse().find(x=>x.current_band);document.getElementById("latest-band").textContent=latest?`Band ${latest.current_band}`:"No scored result yet";document.getElementById("history-body").innerHTML=[...history].reverse().map(f=>`<tr><td>${escapeHtml(f.assessments?.title)}</td><td>${escapeHtml(f.assessments?.topics?.topic_name)}</td><td>${typeNames[f.assessments?.assessment_type]}</td><td>${f.score==null?"–":`${f.score}/${f.assessments.total_marks}`}</td><td>${f.percentage==null?"–":`${f.percentage}%`}</td><td>${f.current_band??"–"}</td><td><span class="badge ${f.self_evaluation}">${f.self_evaluation}</span></td><td>${escapeHtml(f.revision_comment)}</td></tr>`).join("")||"<tr><td colspan='8'>No feedback submitted yet.</td></tr>";renderCharts();}
function renderCharts(){const map={timed_question:"timed-chart",progress_check:"progress-chart",prelim:"prelim-chart"};for(const[type,canvasId]of Object.entries(map)){const rows=history.filter(x=>x.assessments?.assessment_type===type&&x.current_band);charts[type]?.destroy();charts[type]=new Chart(document.getElementById(canvasId),{type:"line",data:{labels:rows.map(x=>x.assessments.title),datasets:[{label:"Current band",data:rows.map(x=>x.current_band),borderColor:"#2563eb",backgroundColor:"#2563eb",tension:.2},{label:"Target band",data:rows.map(()=>pupil.target_band),borderColor:"#dc2626",borderDash:[7,5],pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{afterLabel:context=>{if(context.datasetIndex!==0)return"";const r=rows[context.dataIndex];return`${r.percentage}% · ${r.assessments.topics?.topic_name}`;}}}},scales:{y:{reverse:true,min:1,max:9,ticks:{stepSize:1},title:{display:true,text:"Band"}},x:{ticks:{maxRotation:45,minRotation:0}}}}});}}
document.getElementById("password-form").addEventListener("submit",async e=>{e.preventDefault();const message=document.getElementById("password-message"),password=document.getElementById("new-password").value;if(password!==document.getElementById("confirm-password").value)return showMessage(message,"The passwords do not match.");const{error}=await db.auth.updateUser({password});if(error)return showMessage(message,error.message);const update=await db.rpc("complete_password_change");if(update.error)return showMessage(message,update.error.message);document.getElementById("password-card").classList.add("hidden");document.getElementById("portal").classList.remove("hidden");await initialisePortal();});
async function initialisePortal(){await loadPupil();await loadAssessments();await loadHistory();}
(async()=>{const result=await db.auth.getUser();user=result.data.user;if(!user)return window.location.replace("index.html");const{data:profile}=await db.from("profiles").select("role,must_change_password").eq("id",user.id).single();if(profile?.role!=="pupil")return signOut();if(profile.must_change_password)document.getElementById("password-card").classList.remove("hidden");else{document.getElementById("portal").classList.remove("hidden");await initialisePortal();}})();
